version: '3.7'

services:
  web:
    build: ./src
    depends_on:
      - db
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER_NAME:$POSTGRES_USER_PASSWORD@db/$POSTGRES_DB_NAME
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$POSTGRES_USER_NAME
      - POSTGRES_PASSWORD=$POSTGRES_USER_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME

volumes:
  postgres_data: